## NumPy

In [5]:
import numpy as np

In [4]:
L1 = [1,2,3,4,5,6,7,8]

In [6]:
x1 = np.array(L1)
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
x2 = np.array(L1, dtype = '')
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

- bool_
- int_, intc, intp, int8, int16, int32, int64
- uint8, uint16, uint32, uint64
- float_, float16 (+/-999.9999999e99999), float32, float64 
- complex_, complex64, complex128 (a+bi, a,b $\in$ float_)


In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(3,12,dtype = int)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [55]:
np.linspace(1,7,12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [57]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
x.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
x.reshape((3,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [8]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.transpose(x)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [12]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
np.resize(x, (5, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

## Ejercicios
1. Crear un array de datos con valores entre 5 y 120
2. Crear una matriz 4x4 con los valores desde 0 hasta 15
3. Crear la identidad 7x7
4. Crear un array de 20 elementos y transformarlos en una matriz 5x4
5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme


In [25]:
ej1 = np.arange(5, 121)
ej1

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

In [8]:
ej2 = np.arange(16)
ej2.reshape((4, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
ej3 = np.eye(7)
ej3

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [20]:
ej4 = np.arange(20)
ej4.reshape((5, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [24]:
ej5 = np.linspace(0,5,20)
ej5

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

## Propiedad de los arrays

In [3]:
x = np.arange(12)
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
x.ndim

2

In [35]:
x.shape

(3, 4)

In [37]:
x.size

12

In [39]:
x.dtype

dtype('int32')

In [41]:
x.itemsize

4

In [6]:
x[2]

array([ 8,  9, 10, 11])

In [8]:
x[2,1]

9

In [12]:
x[:,2]

array([ 2,  6, 10])

In [14]:
x.shape = (4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
x[1:3, 0:2]

array([[3, 4],
       [6, 7]])

In [4]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
y[3:8]

array([3, 4, 5, 6, 7])

In [8]:
y[1:7:2]

array([1, 3, 5])

In [10]:
z = np. arange(10, 6, -1)
z

array([10,  9,  8,  7])

In [24]:
a = np.array([1,5])
a
y[a]

array([1, 5])

In [26]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [30]:
cond = (x<25)
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [32]:
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
x[12:24] = 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [38]:
x[13:16] = [6,9,12]
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [49]:
x.dtype

dtype('int32')

In [51]:
x[5] = 3.1415
x

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [53]:
x[8] = 1.2j

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [55]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Copias y vistas de arrays

In [58]:
x = np.arange(10)

In [60]:
y = x

In [66]:
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
z = x.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
z is x

False

In [74]:
y is x

True

In [80]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
t = x.view()
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [92]:
t.shape = (5, 2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [94]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [96]:
t is x

False

In [98]:
t[0, 0] = 100
print(x)

[[100   1   2   3   4]
 [  5   6   7   8   9]]


In [100]:
t

array([[100,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]])

In [102]:
s = x[0:2, 1:3]
s

array([[1, 2],
       [6, 7]])

In [104]:
s[:]=5
s

array([[5, 5],
       [5, 5]])

In [106]:
x

array([[100,   5,   5,   3,   4],
       [  5,   5,   5,   8,   9]])

In [108]:
y

array([[100,   5,   5,   3,   4],
       [  5,   5,   5,   8,   9]])

In [110]:
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Funciones Universales (ufunc)
- Unarias: sqrt, sin, cos, **2
- Binarias: maximum, minimun

In [15]:
x = np.arange(10)
x 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
x-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [26]:
x*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [28]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [32]:
alpha = np.linspace(0, 2*np.pi, 4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [34]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [36]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [38]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [40]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [42]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [44]:
np.power(3, x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683], dtype=int32)

In [46]:
np.power(x, 2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [52]:
np.log(x)

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_15084\1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [50]:
np.log2(x)

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_15084\3275510840.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(x)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [54]:
np.log10(x)

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_15084\1114196279.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(x)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [56]:
np.sum(x)

45

In [58]:
np.nansum(x)

45

In [60]:
np.prod(x)

0

In [62]:
np.mean(x)

4.5

In [64]:
np.median(x)

4.5

In [66]:
np.min(x)

0

In [68]:
np.max(x)

9

In [70]:
np.std(x)

2.8722813232690143

In [72]:
np.var(x)

8.25

In [74]:
np.argmin(x)

0

In [76]:
np.argmax(x)

9

In [78]:
np.percentile(x, q=0.95)

0.08549999999999999

In [80]:
y = np.array([True, True, False, True])

In [82]:
np.any(y)

True

In [84]:
np.all(y)

False

In [86]:
np.random.seed(2019)
z = np.random.random((3,5))
z

array([[0.90348221, 0.39308051, 0.62396996, 0.6378774 , 0.88049907],
       [0.29917202, 0.70219827, 0.90320616, 0.88138193, 0.4057498 ],
       [0.45244662, 0.26707032, 0.16286487, 0.8892147 , 0.14847623]])

In [88]:
z.sum()

8.550690063213514

In [90]:
z.sum(axis=0)

array([1.65510085, 1.3623491 , 1.69004099, 2.40847402, 1.43472509])

In [ ]:
z.sum(axis=1)