## Temas 1 - Matrices
Vamos a ver cómo crear una matriz utilizando la librería `numpy`

In [2]:
row = [1,2,3]
row

[1, 2, 3]

In [4]:
col = [[1],[2],[3]]
col

[[1], [2], [3]]

In [8]:
M = [[1,2,3],[4,5,6],[7,8,9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
M[1][1]

5

In [12]:
M[0][0]

1

In [7]:
import numpy as np

In [13]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float)
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.shape(M)

(3, 3)

In [29]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,0],[1,-1]])
print("a \n",A)
print("b \n",B)

a 
 [[1 2]
 [3 4]]
b 
 [[ 3  0]
 [ 1 -1]]


In [31]:
print(A+B)

[[4 2]
 [4 3]]


In [33]:
print(A.dot(B))

[[ 5 -2]
 [13 -4]]


In [37]:
print(A.trace())

5


In [39]:
print(A.transpose())

[[1 3]
 [2 4]]


In [43]:
np.linalg.matrix_rank(A)

2

In [47]:
np.linalg.matrix_power(A,5)

array([[1069, 1558],
       [2337, 3406]])

In [49]:
np.linalg.det(A)

-2.0000000000000004

In [51]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [53]:
print(np.linalg.inv(A).dot(A))

[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


In [55]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [57]:
np.linalg.matrix_rank(X)

2

In [63]:
np.linalg.inv(X)

LinAlgError: Singular matrix

In [65]:
## np.linalg.inv(np.array([[1,2,3],[4,5,6]]))

LinAlgError: Last 2 dimensions of the array must be square

## Tarea 5

In [6]:
import math
def resolver_ecuacion_segundo_grado(a,b,c):
    discriminante = b**2 - 4*a*c
    if discriminante > 0:
        x1 = (-b+math.sqrt(discriminante))/(2*a)
        x2 = (-b-math.sqrt(discriminante))/(2*a)
        print(f"Las soluciones son x1 = {x1} y x2 = {x2}")
    elif discriminante == 0:
        x = -b/(2*a)
        print(f"Hay una única solución: x = {x}")
    else:
        print("No hay soluciones reales")

In [8]:
resolver_ecuacion_segundo_grado(1, -3, 2)

Las soluciones son x1 = 2.0 y x2 = 1.0


**Ejercicio 2**

In [11]:
def es_palindromo(frase):
    frase_limpia = ''.join(char.lower() for char in frase if char.isalnum())
    if frase_limpia == frase_limpia[::-1]:
        print("La frase es un palíndromo")
    else:
        print("La frase no es un palíndromo")

In [16]:
frase = input("Introduce una frase: ")
es_palindromo(frase)

Introduce una frase:  ama


La frase es un palíndromo


**Ejercicio 3**

In [25]:
#Diccionario comprimidos
diccionario = {i: math.sqrt(i) for i in range(1,11)}
print(diccionario)

{1: 1.0, 2: 1.4142135623730951, 3: 1.7320508075688772, 4: 2.0, 5: 2.23606797749979, 6: 2.449489742783178, 7: 2.6457513110645907, 8: 2.8284271247461903, 9: 3.0, 10: 3.1622776601683795}


**Ejercicio 4**

In [32]:
morse_code_dict = {
    'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.', 'G': '--.', 'H': '....', 'I': '..',
    'J': '.---', 'K': '-.-', 'L': '.-..', 'M': '--', 'N': '-.', 'O': '---', 'P': '.--.', 'Q': '--.-', 'R': '.-.',
    'S': '...', 'T': '-', 'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-', 'Y': '-.--', 'Z': '--..', '0': '-----',
    '1': '.----', '2': '..---', '3': '...--', '4': '....-', '5': '.....', '6': '-....', '7': '--...', '8': '---..',
    '9': '----.', 'Ñ': '--.--', '.': '.-.-.-', ',': '--..--', '?': '..--..', "'": '.----.', '!': '-.-.--',
    '/': '-..-.', '(': '-.--.', ')': '-.--.-', '&': '.-...', ':': '---...', ';': '-.-.-.', '=': '-...-', '+': '.-.-.',
    '-': '-....-', '_': '..--.-', '"': '.-..-.', '$': '...-..-', '@': '.--.-.', ' ': ' '
}
def convertir_a_morse(frase):
    # Convertir la frase a mayúsculas para que coincida con las claves del diccionario
    frase = frase.upper() 
    # Inicializar una lista para almacenar el código morse
    morse_frase = []
    # Convertir cada letra de la frase a su código morse
    for char in frase:
        if char in morse_code_dict:
            morse_frase.append(morse_code_dict[char])
        else:
            # Si el carácter no está en el diccionario, añadir un espacio como separador
            morse_frase.append(' ')
    # Unir todos los símbolos de morse con un espacio para separar las letras
    return ' '.join(morse_frase)

frase = input("Introduce una frase: ")
print("La frase en código morse es:")
print(convertir_a_morse(frase))

Introduce una frase:  hay clases el día de hoy?


La frase en código morse es:
.... .- -.--   -.-. .-.. .- ... . ...   . .-..   -..   .-   -.. .   .... --- -.-- ..--..


**Ejercicio 5**

In [45]:
def claves_comunes(dic1, dic2):
    comunes = []
    for clave in dic1:
        if clave in dic2:
            comunes.append(clave)
    return comunes
diccionario1 = {
    'a': 1,
    'b': 2,
    'c': 3
}

diccionario2 = {
    'b': 4,
    'c': 5,
    'd': 6
}

print(diccionario1.keys())
print(diccionario2.keys())
print(claves_comunes(diccionario1, diccionario2))


dict_keys(['a', 'b', 'c'])
dict_keys(['b', 'c', 'd'])
['b', 'c']


**Ejercicio 6**

In [4]:
def es_primo(N):
    if N <= 1:
        return False;
    if N == 2:
        return True;
    for x in range(2,N):
        if N % x == 0:
            return False;
    return True

N = int(input("Introduce un número: "))
if es_primo(N):
    print(f"{N} Es un número primo")
else:
    print(f"{N} no es un número primo")


Introduce un número:  13233489534


13233489534 no es un número primo


**Ejercicio 7**

In [15]:
def capitalizar_primera_letra():
    frase = input("Introduce una frase: ")
    frase_capitalizada = frase.title()
    print("Frase con la primera letra de cada palabra en mayúscula")
    print(frase_capitalizada)

capitalizar_primera_letra()

Introduce una frase:  que tal


Frase con la primera letra de cada palabra en mayúscula
Que Tal


**Ejercicio 8**

In [20]:
def calcular_mcd(a,b):
    while b != 0:
        a, b = b, a % b
    return a

num1 = int(input("Introduce el primer número: "))
num2 = int(input("Introduce el segundo número: "))
mcd = calcular_mcd(num1, num2)
print(f"El máximo común divisor de {num1} y {num2} es {mcd}")

Introduce el primer número:  12
Introduce el segundo número:  3


El máximo común divisor de 12 y 3 es 3


**Ejercicio 10**

In [24]:
def ordenar_nombres(lista_nombres):
    orden_alfabetico = sorted(lista_nombres)
    orden_alfabetico_invertido = sorted(lista_nombres, reverse = True)
    orden_longitud = sorted(lista_nombres, key = len)
    return orden_alfabetico, orden_alfabetico_invertido, orden_longitud

nombres = ["Juan", "María", "Carlos", "Ana", "Pedro", "Luisa", "Pablo"]
orden_alfabetico, orden_alfabetico_invertido, orden_longitud = ordenar_nombres(nombres)
print("Orden alfabético:", orden_alfabetico)
print("Orden alfabético invertido:", orden_alfabetico_invertido)
print("Orden por longitud:", orden_longitud)

Orden alfabético: ['Ana', 'Carlos', 'Juan', 'Luisa', 'María', 'Pablo', 'Pedro']
Orden alfabético invertido: ['Pedro', 'Pablo', 'María', 'Luisa', 'Juan', 'Carlos', 'Ana']
Orden por longitud: ['Ana', 'Juan', 'María', 'Pedro', 'Luisa', 'Pablo', 'Carlos']
